const videosData = [{
        videoId: "video01",
        title: "Learn React in 30 Minutes",
        category: "Education",
        embedUrl: "https://www.youtube.com/embed/hQAHSlTtcmY",
        thumbnailUrl: "https://img.youtube.com/vi/hQAHSlTtcmY/hqdefault.jpg",
        description: "A quick tutorial to get started with React.",
        channelId: "channel01",
        uploader: "Code Academy",
        views: 15200,
        likes: 1023,
        dislikes: 45,
        uploadDate: "2024-09-20",
        comments: [{
                commentId: "c01",
                userId: "u01",
                userName: "John Doe",
                userAvatar: "https://randomuser.me/api/portraits/men/11.jpg",
                text: "Great video! Very helpful 🚀🔥",
                likes: 34,
                dislikes: 0,
                timestamp: "2024-09-21T08:30:00Z",
            },
            {
                commentId: "c02",
                userId: "u02",
                userName: "Emma Watson",
                userAvatar: "https://randomuser.me/api/portraits/women/22.jpg",
                text: "I finally understand hooks! ❤️",
                likes: 19,
                dislikes: 1,
                timestamp: "2024-09-21T10:12:00Z",
            },
        ],
    },
    {
        videoId: "video02",
        title: "JavaScript Basics for Beginners",
        category: "Education",
        embedUrl: "https://www.youtube.com/embed/PlbupGCBV6w",
        thumbnailUrl: "https://img.youtube.com/vi/PlbupGCBV6w/hqdefault.jpg",
        description: "Learn the fundamentals of JavaScript.",
        channelId: "channel02",
        uploader: "Telusko",
        views: 25000,
        likes: 1500,
        dislikes: 30,
        uploadDate: "2024-08-10",
        comments: [{
            commentId: "c03",
            userId: "u03",
            userName: "Coding Nerd",
            userAvatar: "https://randomuser.me/api/portraits/men/33.jpg",
            text: "JS is the foundation of everything 💻",
            likes: 50,
            dislikes: 2,
            timestamp: "2024-08-11T12:00:00Z",
        }, ],
    },
    {
        videoId: "video03",
        title: "Frontend Interview Experience",
        category: "Career",
        embedUrl: "https://www.youtube.com/embed/ILaXhmTraQ4",
        thumbnailUrl: "https://img.youtube.com/vi/ILaXhmTraQ4/hqdefault.jpg",
        description: "Sharing my frontend interview journey.",
        channelId: "channel03",
        uploader: "Code Academy",
        views: 32000,
        likes: 1800,
        dislikes: 50,
        uploadDate: "2024-07-15",
        comments: [{
            commentId: "c04",
            userId: "u04",
            userName: "Priya Sharma",
            userAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
            text: "This helped me crack my interview 😍✨",
            likes: 78,
            dislikes: 3,
            timestamp: "2024-07-16T09:45:00Z",
        }, ],
    },

];

export default videosData;