const videosData = [{
        videoId: "video01",
        title: "Learn React in 30 Minutes",
        category: "Education",
        embedUrl: "https://www.youtube.com/embed/hQAHSlTtcmY",
        thumbnailUrl: "https://img.youtube.com/vi/hQAHSlTtcmY/hqdefault.jpg",
        description: "A quick tutorial to get started with React.",
        channelId: "channel01",
        uploader: "Code Academy",
        views: 15200,
        likes: 1023,
        dislikes: 45,
        uploadDate: "2024-09-20",
        comments: [{
                commentId: "c01",
                userId: "u01",
                userName: "John Doe",
                userAvatar: "https://randomuser.me/api/portraits/men/11.jpg",
                text: "Great video! Very helpful 🚀🔥",
                likes: 34,
                dislikes: 0,
                timestamp: "2024-09-21T08:30:00Z",
            },
            {
                commentId: "c02",
                userId: "u02",
                userName: "Emma Watson",
                userAvatar: "https://randomuser.me/api/portraits/women/22.jpg",
                text: "I finally understand hooks! ❤️",
                likes: 19,
                dislikes: 1,
                timestamp: "2024-09-21T10:12:00Z",
            },
        ],
    },
    /*  {
        videoId: "video02",
        title: "JavaScript Basics for Beginners",
        category: "Education",
        embedUrl: "https://www.youtube.com/embed/PlbupGCBV6w",
        thumbnailUrl: "https://img.youtube.com/vi/PlbupGCBV6w/hqdefault.jpg",
        description: "Learn the fundamentals of JavaScript.",
        channelId: "channel02",
        uploader: "Telusko",
        views: 25000,
        likes: 1500,
        dislikes: 30,
        uploadDate: "2024-08-10",
        comments: [{
            commentId: "c03",
            userId: "u03",
            userName: "Coding Nerd",
            userAvatar: "https://randomuser.me/api/portraits/men/33.jpg",
            text: "JS is the foundation of everything 💻",
            likes: 50,
            dislikes: 2,
            timestamp: "2024-08-11T12:00:00Z",
        }, ],
    },
    {
        videoId: "video03",
        title: "Frontend Interview Experience",
        category: "Career",
        embedUrl: "https://www.youtube.com/embed/ILaXhmTraQ4",
        thumbnailUrl: "https://img.youtube.com/vi/ILaXhmTraQ4/hqdefault.jpg",
        description: "Sharing my frontend interview journey.",
        channelId: "channel03",
        uploader: "Code Academy",
        views: 32000,
        likes: 1800,
        dislikes: 50,
        uploadDate: "2024-07-15",
        comments: [{
            commentId: "c04",
            userId: "u04",
            userName: "Priya Sharma",
            userAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
            text: "This helped me crack my interview 😍✨",
            likes: 78,
            dislikes: 3,
            timestamp: "2024-07-16T09:45:00Z",
        }, ],
    },
    {
        videoId: "video04",
        title: "India's Got Talent Performance",
        category: "Entertainment",
        embedUrl: "https://www.youtube.com/embed/mLIOOc2uRXI",
        thumbnailUrl: "https://img.youtube.com/vi/mLIOOc2uRXI/hqdefault.jpg",
        description: "Amazing performance from India's Got Talent.",
        channelId: "channel04",
        uploader: "StarPlus",
        views: 120000,
        likes: 7500,
        dislikes: 200,
        uploadDate: "2024-06-05",
        comments: [{
            commentId: "c05",
            userId: "u05",
            userName: "Raj Patel",
            userAvatar: "https://randomuser.me/api/portraits/men/55.jpg",
            text: "Mind-blowing performance 👏🔥",
            likes: 500,
            dislikes: 10,
            timestamp: "2024-06-06T15:00:00Z",
        }, ],
    },
    {
        videoId: "video05",
        title: "Best of AR Rahman Songs",
        category: "Music",
        embedUrl: "https://www.youtube.com/embed/tgbNymZ7vqY",
        thumbnailUrl: "https://img.youtube.com/vi/tgbNymZ7vqY/hqdefault.jpg",
        description: "A compilation of AR Rahman’s greatest hits.",
        channelId: "channel05",
        uploader: "Sony Music",
        views: 890000,
        likes: 52000,
        dislikes: 900,
        uploadDate: "2024-05-01",
        comments: [{
            commentId: "c06",
            userId: "u06",
            userName: "Ayesha Khan",
            userAvatar: "https://randomuser.me/api/portraits/women/66.jpg",
            text: "Goosebumps every single time 🎶😍",
            likes: 2000,
            dislikes: 20,
            timestamp: "2024-05-02T09:00:00Z",
        }, ],
    },
    {
        videoId: "video06",
        title: "Top 10 PUBG Plays",
        category: "Gaming",
        embedUrl: "https://www.youtube.com/embed/7QUtEmBT_-w",
        thumbnailUrl: "https://img.youtube.com/vi/7QUtEmBT_-w/hqdefault.jpg",
        description: "Insane PUBG highlights from pro players.",
        channelId: "channel06",
        uploader: "Gaming World",
        views: 450000,
        likes: 30000,
        dislikes: 1200,
        uploadDate: "2024-04-20",
        comments: [{
            commentId: "c07",
            userId: "u07",
            userName: "GamerX",
            userAvatar: "https://randomuser.me/api/portraits/men/77.jpg",
            text: "That headshot at 3:21 😱🔥",
            likes: 900,
            dislikes: 15,
            timestamp: "2024-04-21T14:15:00Z",
        }, ],
    },
    {
        videoId: "video07",
        title: "SpaceX Starship Launch",
        category: "Tech",
        embedUrl: "https://www.youtube.com/embed/0qo78R_yYFA",
        thumbnailUrl: "https://img.youtube.com/vi/0qo78R_yYFA/hqdefault.jpg",
        description: "Historic launch of SpaceX Starship.",
        channelId: "channel07",
        uploader: "SpaceX",
        views: 2000000,
        likes: 180000,
        dislikes: 5000,
        uploadDate: "2024-03-10",
        comments: [{
            commentId: "c08",
            userId: "u08",
            userName: "Tech Lover",
            userAvatar: "https://randomuser.me/api/portraits/men/88.jpg",
            text: "We’re living in the future 🚀🌌",
            likes: 15000,
            dislikes: 50,
            timestamp: "2024-03-11T08:00:00Z",
        }, ],
    },
    {
        videoId: "video08",
        title: "Virat Kohli’s Century Highlights",
        category: "Sports",
        embedUrl: "https://www.youtube.com/embed/YYjBQKIOb-w",
        thumbnailUrl: "https://img.youtube.com/vi/YYjBQKIOb-w/hqdefault.jpg",
        description: "Kohli’s best innings of the season.",
        channelId: "channel08",
        uploader: "Star Sports",
        views: 950000,
        likes: 70000,
        dislikes: 2200,
        uploadDate: "2024-02-14",
        comments: [{
            commentId: "c09",
            userId: "u09",
            userName: "Rahul Dravid",
            userAvatar: "https://randomuser.me/api/portraits/men/99.jpg",
            text: "King Kohli 👑🔥",
            likes: 3000,
            dislikes: 25,
            timestamp: "2024-02-15T10:00:00Z",
        }, ],
    },
    {
        videoId: "video09",
        title: "Yoga for Beginners - Morning Routine",
        category: "Health",
        embedUrl: "https://www.youtube.com/embed/v7AYKMP6rOE",
        thumbnailUrl: "https://img.youtube.com/vi/v7AYKMP6rOE/hqdefault.jpg",
        description: "Start your day with this simple yoga flow.",
        channelId: "channel09",
        uploader: "Yoga With Adriene",
        views: 670000,
        likes: 42000,
        dislikes: 800,
        uploadDate: "2024-01-05",
        comments: [{
            commentId: "c10",
            userId: "u10",
            userName: "Sophia Lee",
            userAvatar: "https://randomuser.me/api/portraits/women/10.jpg",
            text: "This routine makes me feel so calm ☀️🧘‍♀️",
            likes: 500,
            dislikes: 3,
            timestamp: "2024-01-06T07:30:00Z",
        }, ],
    },
    {
        videoId: "video10",
        title: "Street Food Tour in Delhi",
        category: "Travel",
        embedUrl: "https://www.youtube.com/embed/6RzCvqM6S3Q",
        thumbnailUrl: "https://img.youtube.com/vi/6RzCvqM6S3Q/hqdefault.jpg",
        description: "Exploring the best street food in Delhi, India.",
        channelId: "channel10",
        uploader: "Food Ranger",
        views: 1200000,
        likes: 95000,
        dislikes: 1500,
        uploadDate: "2023-12-20",
        comments: [{
            commentId: "c11",
            userId: "u11",
            userName: "Arjun Mehta",
            userAvatar: "https://randomuser.me/api/portraits/men/12.jpg",
            text: "Now I’m hungry 🤤🔥",
            likes: 1200,
            dislikes: 8,
            timestamp: "2023-12-21T12:15:00Z",
        }, ],
    },
    {
        videoId: "video11",
        title: "Python Full Course for Beginners",
        category: "Education",
        embedUrl: "https://www.youtube.com/embed/_uQrJ0TkZlc",
        thumbnailUrl: "https://img.youtube.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
        description: "Learn Python from scratch with this complete course.",
        channelId: "channel11",
        uploader: "Programming with Mosh",
        views: 2100000,
        likes: 180000,
        dislikes: 6000,
        uploadDate: "2023-11-01",
        comments: [{
            commentId: "c12",
            userId: "u12",
            userName: "Michael Scott",
            userAvatar: "https://randomuser.me/api/portraits/men/13.jpg",
            text: "Python is so beginner-friendly 🐍💻",
            likes: 8000,
            dislikes: 50,
            timestamp: "2023-11-02T09:00:00Z",
        }, ],
    },
    {
        videoId: "video12",
        title: "Marvel Avengers Tribute",
        category: "Entertainment",
        embedUrl: "https://www.youtube.com/embed/eOrNdBpGMv8",
        thumbnailUrl: "https://img.youtube.com/vi/eOrNdBpGMv8/hqdefault.jpg",
        description: "A tribute to the Avengers saga.",
        channelId: "channel12",
        uploader: "Marvel Studios",
        views: 8000000,
        likes: 600000,
        dislikes: 12000,
        uploadDate: "2023-10-15",
        comments: [{
            commentId: "c13",
            userId: "u13",
            userName: "Tony Stark",
            userAvatar: "https://randomuser.me/api/portraits/men/14.jpg",
            text: "Avengers... Assemble! 🦸‍♂️🔥",
            likes: 15000,
            dislikes: 100,
            timestamp: "2023-10-16T11:20:00Z",
        }, ],
    },
    {
        videoId: "video13",
        title: "FIFA World Cup 2022 Final Highlights",
        category: "Sports",
        embedUrl: "https://www.youtube.com/embed/qr6ar3xJL_Q",
        thumbnailUrl: "https://img.youtube.com/vi/qr6ar3xJL_Q/hqdefault.jpg",
        description: "Argentina vs France final match highlights.",
        channelId: "channel13",
        uploader: "FIFA",
        views: 15000000,
        likes: 1200000,
        dislikes: 30000,
        uploadDate: "2023-09-18",
        comments: [{
            commentId: "c14",
            userId: "u14",
            userName: "Lionel Messi",
            userAvatar: "https://randomuser.me/api/portraits/men/15.jpg",
            text: "One of the greatest matches ever ⚽🏆",
            likes: 25000,
            dislikes: 200,
            timestamp: "2023-09-19T08:00:00Z",
        }, ],
    },
    {
        videoId: "video14",
        title: "Apple iPhone 15 Review",
        category: "Tech",
        embedUrl: "https://www.youtube.com/embed/8rU8WZjk6EY",
        thumbnailUrl: "https://img.youtube.com/vi/8rU8WZjk6EY/hqdefault.jpg",
        description: "Full review of the latest iPhone 15.",
        channelId: "channel14",
        uploader: "MKBHD",
        views: 3200000,
        likes: 250000,
        dislikes: 7000,
        uploadDate: "2023-08-05",
        comments: [{
            commentId: "c15",
            userId: "u15",
            userName: "David Kim",
            userAvatar: "https://randomuser.me/api/portraits/men/16.jpg",
            text: "That dynamic island is 🔥📱",
            likes: 6000,
            dislikes: 40,
            timestamp: "2023-08-06T10:00:00Z",
        }, ],
    },
    {
        videoId: "video15",
        title: "Shinchan Funny Moments Compilation",
        category: "Comedy",
        embedUrl: "https://www.youtube.com/embed/OoBnCEGHBow",
        thumbnailUrl: "https://img.youtube.com/vi/OoBnCEGHBow/hqdefault.jpg",
        description: "Best funny moments of Shinchan.",
        channelId: "channel15",
        uploader: "Cartoon Network",
        views: 4500000,
        likes: 330000,
        dislikes: 9000,
        uploadDate: "2023-07-12",
        comments: [{
            commentId: "c16",
            userId: "u16",
            userName: "Nisha Gupta",
            userAvatar: "https://randomuser.me/api/portraits/women/17.jpg",
            text: "Can’t stop laughing 😂🔥",
            likes: 7000,
            dislikes: 50,
            timestamp: "2023-07-13T14:30:00Z",
        }, ],
    },
    {
        videoId: "video16",
        title: "Meditation Music for Relaxation",
        category: "Music",
        embedUrl: "https://www.youtube.com/embed/2OEL4P1Rz04",
        thumbnailUrl: "https://img.youtube.com/vi/2OEL4P1Rz04/hqdefault.jpg",
        description: "Relaxing meditation music for stress relief.",
        channelId: "channel16",
        uploader: "Peaceful Mind",
        views: 5000000,
        likes: 400000,
        dislikes: 7000,
        uploadDate: "2023-06-01",
        comments: [{
            commentId: "c17",
            userId: "u17",
            userName: "Olivia Brown",
            userAvatar: "https://randomuser.me/api/portraits/women/18.jpg",
            text: "Listening before sleep 😴💤",
            likes: 2000,
            dislikes: 10,
            timestamp: "2023-06-02T21:00:00Z",
        }, ],
    },
    {
        videoId: "video17",
        title: "Tesla Cybertruck Test Drive",
        category: "Tech",
        embedUrl: "https://www.youtube.com/embed/m7atGkba-Z8",
        thumbnailUrl: "https://img.youtube.com/vi/m7atGkba-Z8/hqdefault.jpg",
        description: "First impressions of Tesla Cybertruck.",
        channelId: "channel17",
        uploader: "Tesla",
        views: 2700000,
        likes: 210000,
        dislikes: 6000,
        uploadDate: "2023-05-15",
        comments: [{
            commentId: "c18",
            userId: "u18",
            userName: "Elon Musk",
            userAvatar: "https://randomuser.me/api/portraits/men/19.jpg",
            text: "This is the future of trucks ⚡🚙",
            likes: 15000,
            dislikes: 70,
            timestamp: "2023-05-16T18:00:00Z",
        }, ],
    },
    {
        videoId: "video18",
        title: "Cooking Pasta Like a Pro",
        category: "Food",
        embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
        description: "Learn to make restaurant-style pasta.",
        channelId: "channel18",
        uploader: "Tasty",
        views: 1800000,
        likes: 140000,
        dislikes: 5000,
        uploadDate: "2023-04-08",
        comments: [{
            commentId: "c19",
            userId: "u19",
            userName: "Maria Rossi",
            userAvatar: "https://randomuser.me/api/portraits/women/20.jpg",
            text: "This recipe is authentic 🇮🇹🍝",
            likes: 3500,
            dislikes: 20,
            timestamp: "2023-04-09T11:00:00Z",
        }, ],
    },
    {
        videoId: "video19",
        title: "Motivational Speech by Steve Jobs",
        category: "Motivation",
        embedUrl: "https://www.youtube.com/embed/UF8uR6Z6KLc",
        thumbnailUrl: "https://img.youtube.com/vi/UF8uR6Z6KLc/hqdefault.jpg",
        description: "Steve Jobs’ Stanford Commencement Speech.",
        channelId: "channel19",
        uploader: "Stanford",
        views: 25000000,
        likes: 2100000,
        dislikes: 55000,
        uploadDate: "2023-03-01",
        comments: [{
            commentId: "c20",
            userId: "u20",
            userName: "Chris Evans",
            userAvatar: "https://randomuser.me/api/portraits/men/21.jpg",
            text: "Stay hungry, stay foolish 🍎🔥",
            likes: 12000,
            dislikes: 100,
            timestamp: "2023-03-02T12:00:00Z",
        }, ],
    },
    {
        videoId: "video20",
        title: "Nature Documentary - Planet Earth",
        category: "Documentary",
        embedUrl: "https://www.youtube.com/embed/aETNYyrqNYE",
        thumbnailUrl: "https://img.youtube.com/vi/aETNYyrqNYE/hqdefault.jpg",
        description: "Exploring the beauty of our planet.",
        channelId: "channel20",
        uploader: "BBC Earth",
        views: 12000000,
        likes: 980000,
        dislikes: 20000,
        uploadDate: "2023-02-14",
        comments: [{
            commentId: "c21",
            userId: "u21",
            userName: "Nature Lover",
            userAvatar: "https://randomuser.me/api/portraits/men/22.jpg",
            text: "Breathtaking visuals 🌍🌿",
            likes: 8000,
            dislikes: 40,
            timestamp: "2023-02-15T09:30:00Z",
        }, ],
    },
 */
];

export default videosData;